import type { CrudModuleConfig, ModuleCategory } from '@/types/admin';

export const ADMIN_MODULES: Record<string, CrudModuleConfig> = {
  users: {
    slug: 'users',
    title: 'Пользователи',
    apiEndpoint: '/users',
    searchField: 'имени',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Имя', sortable: true },
      { key: 'email', header: 'Email', sortable: true },
      { key: 'phone', header: 'Телефон' },
      { key: 'isActive', header: 'Активен', render: (v) => (v ? 'Да' : 'Нет') },
    ],
    formFields: [
      { key: 'name', label: 'Имя', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'phone', label: 'Телефон', type: 'text' },
      { key: 'password', label: 'Пароль', type: 'text', required: true },
      { key: 'isActive', label: 'Активен', type: 'checkbox' },
    ],
  },
  projects: {
    slug: 'projects',
    title: 'Проекты',
    apiEndpoint: '/projects',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'status', header: 'Статус', sortable: true },
      { key: 'startDate', header: 'Начало' },
      { key: 'endDate', header: 'Окончание' },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text', required: true },
      { key: 'description', label: 'Описание', type: 'textarea' },
      { key: 'status', label: 'Статус', type: 'select', options: [
        { value: 'planning', label: 'Планирование' },
        { value: 'active', label: 'Активный' },
        { value: 'completed', label: 'Завершён' },
        { value: 'on_hold', label: 'На паузе' },
      ]},
      { key: 'startDate', label: 'Дата начала', type: 'date' },
      { key: 'endDate', label: 'Дата окончания', type: 'date' },
    ],
  },
  tasks: {
    slug: 'tasks',
    title: 'Задачи',
    apiEndpoint: '/tasks',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'title', header: 'Название', sortable: true },
      { key: 'status', header: 'Статус', sortable: true },
      { key: 'priority', header: 'Приоритет', sortable: true },
      { key: 'dueDate', header: 'Срок' },
    ],
    formFields: [
      { key: 'title', label: 'Название', type: 'text', required: true },
      { key: 'description', label: 'Описание', type: 'textarea' },
      { key: 'status', label: 'Статус', type: 'select', options: [
        { value: 'todo', label: 'К выполнению' },
        { value: 'in_progress', label: 'В работе' },
        { value: 'done', label: 'Выполнена' },
      ]},
      { key: 'priority', label: 'Приоритет', type: 'select', options: [
        { value: 'low', label: 'Низкий' },
        { value: 'medium', label: 'Средний' },
        { value: 'high', label: 'Высокий' },
      ]},
      { key: 'dueDate', label: 'Срок', type: 'date' },
    ],
  },
  clients: {
    slug: 'clients',
    title: 'Клиенты',
    apiEndpoint: '/clients',
    searchField: 'имени',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'email', header: 'Email' },
      { key: 'phone', header: 'Телефон' },
      { key: 'contactPerson', header: 'Контактное лицо' },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Телефон', type: 'text' },
      { key: 'contactPerson', label: 'Контактное лицо', type: 'text' },
      { key: 'address', label: 'Адрес', type: 'textarea' },
    ],
  },
  materials: {
    slug: 'materials',
    title: 'Материалы',
    apiEndpoint: '/materials',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'unit', header: 'Ед. изм.' },
      { key: 'quantity', header: 'Кол-во', sortable: true },
      { key: 'price', header: 'Цена', sortable: true },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text', required: true },
      { key: 'unit', label: 'Единица измерения', type: 'text' },
      { key: 'quantity', label: 'Количество', type: 'number' },
      { key: 'price', label: 'Цена', type: 'number' },
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
  equipment: {
    slug: 'equipment',
    title: 'Оборудование',
    apiEndpoint: '/equipment',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'status', header: 'Статус', sortable: true },
      { key: 'location', header: 'Расположение' },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text', required: true },
      { key: 'type', label: 'Тип', type: 'text' },
      { key: 'status', label: 'Статус', type: 'select', options: [
        { value: 'available', label: 'Доступно' },
        { value: 'in_use', label: 'В использовании' },
        { value: 'maintenance', label: 'На обслуживании' },
      ]},
      { key: 'location', label: 'Расположение', type: 'text' },
    ],
  },
  suppliers: {
    slug: 'suppliers',
    title: 'Поставщики',
    apiEndpoint: '/suppliers',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'contactPerson', header: 'Контакт' },
      { key: 'phone', header: 'Телефон' },
      { key: 'email', header: 'Email' },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text', required: true },
      { key: 'contactPerson', label: 'Контактное лицо', type: 'text' },
      { key: 'phone', label: 'Телефон', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'address', label: 'Адрес', type: 'textarea' },
    ],
  },
  documents: {
    slug: 'documents',
    title: 'Документы',
    apiEndpoint: '/documents',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'title', header: 'Название', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'createdAt', header: 'Создан', sortable: true },
    ],
    formFields: [
      { key: 'title', label: 'Название', type: 'text', required: true },
      { key: 'type', label: 'Тип', type: 'select', options: [
        { value: 'contract', label: 'Договор' },
        { value: 'act', label: 'Акт' },
        { value: 'invoice', label: 'Счёт' },
        { value: 'report', label: 'Отчёт' },
        { value: 'other', label: 'Прочее' },
      ]},
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
  payments: {
    slug: 'payments',
    title: 'Платежи',
    apiEndpoint: '/payments',
    searchField: 'описанию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'amount', header: 'Сумма', sortable: true },
      { key: 'status', header: 'Статус', sortable: true },
      { key: 'date', header: 'Дата', sortable: true },
      { key: 'description', header: 'Описание' },
    ],
    formFields: [
      { key: 'amount', label: 'Сумма', type: 'number', required: true },
      { key: 'status', label: 'Статус', type: 'select', options: [
        { value: 'pending', label: 'Ожидает' },
        { value: 'paid', label: 'Оплачен' },
        { value: 'cancelled', label: 'Отменён' },
      ]},
      { key: 'date', label: 'Дата', type: 'date', required: true },
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
  budgets: {
    slug: 'budgets',
    title: 'Бюджеты',
    apiEndpoint: '/budgets',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'totalAmount', header: 'Бюджет', sortable: true },
      { key: 'spentAmount', header: 'Потрачено', sortable: true },
      { key: 'status', header: 'Статус' },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text', required: true },
      { key: 'totalAmount', label: 'Общий бюджет', type: 'number', required: true },
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
  acts: {
    slug: 'acts',
    title: 'Акты',
    apiEndpoint: '/acts',
    searchField: 'номеру',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'number', header: 'Номер', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'date', header: 'Дата', sortable: true },
      { key: 'status', header: 'Статус' },
    ],
    formFields: [
      { key: 'number', label: 'Номер', type: 'text', required: true },
      { key: 'type', label: 'Тип', type: 'text' },
      { key: 'date', label: 'Дата', type: 'date', required: true },
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
  salaries: {
    slug: 'salaries',
    title: 'Зарплата',
    apiEndpoint: '/salaries',
    searchField: 'сотруднику',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'employeeName', header: 'Сотрудник', sortable: true },
      { key: 'amount', header: 'Сумма', sortable: true },
      { key: 'month', header: 'Месяц' },
      { key: 'status', header: 'Статус' },
    ],
    formFields: [
      { key: 'employeeId', label: 'ID сотрудника', type: 'number', required: true },
      { key: 'amount', label: 'Сумма', type: 'number', required: true },
      { key: 'month', label: 'Месяц', type: 'date', required: true },
    ],
  },
  bonuses: {
    slug: 'bonuses',
    title: 'Бонусы',
    apiEndpoint: '/bonuses',
    searchField: 'сотруднику',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'employeeName', header: 'Сотрудник', sortable: true },
      { key: 'amount', header: 'Сумма', sortable: true },
      { key: 'reason', header: 'Причина' },
      { key: 'date', header: 'Дата', sortable: true },
    ],
    formFields: [
      { key: 'employeeId', label: 'ID сотрудника', type: 'number', required: true },
      { key: 'amount', label: 'Сумма', type: 'number', required: true },
      { key: 'reason', label: 'Причина', type: 'text' },
      { key: 'date', label: 'Дата', type: 'date', required: true },
    ],
  },
  'employee-documents': {
    slug: 'employee-documents',
    title: 'Документы сотрудников',
    apiEndpoint: '/employee-documents',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'employeeName', header: 'Сотрудник', sortable: true },
      { key: 'title', header: 'Документ', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'expiryDate', header: 'Истекает' },
    ],
    formFields: [
      { key: 'employeeId', label: 'ID сотрудника', type: 'number', required: true },
      { key: 'title', label: 'Название', type: 'text', required: true },
      { key: 'type', label: 'Тип', type: 'text' },
      { key: 'expiryDate', label: 'Дата истечения', type: 'date' },
    ],
  },
  leaves: {
    slug: 'leaves',
    title: 'Отпуска',
    apiEndpoint: '/leaves',
    searchField: 'сотруднику',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'employeeName', header: 'Сотрудник', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'startDate', header: 'Начало', sortable: true },
      { key: 'endDate', header: 'Окончание' },
      { key: 'status', header: 'Статус' },
    ],
    formFields: [
      { key: 'employeeId', label: 'ID сотрудника', type: 'number', required: true },
      { key: 'type', label: 'Тип', type: 'select', options: [
        { value: 'vacation', label: 'Отпуск' },
        { value: 'sick', label: 'Больничный' },
        { value: 'personal', label: 'Личные' },
      ]},
      { key: 'startDate', label: 'Начало', type: 'date', required: true },
      { key: 'endDate', label: 'Окончание', type: 'date', required: true },
    ],
  },
  attendance: {
    slug: 'attendance',
    title: 'Посещаемость',
    apiEndpoint: '/attendance',
    searchField: 'сотруднику',
    canCreate: false,
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'employeeName', header: 'Сотрудник', sortable: true },
      { key: 'date', header: 'Дата', sortable: true },
      { key: 'checkIn', header: 'Приход' },
      { key: 'checkOut', header: 'Уход' },
    ],
    formFields: [
      { key: 'date', label: 'Дата', type: 'date', required: true },
      { key: 'checkIn', label: 'Приход', type: 'text' },
      { key: 'checkOut', label: 'Уход', type: 'text' },
    ],
  },
  teams: {
    slug: 'teams',
    title: 'Команды',
    apiEndpoint: '/teams',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'leadName', header: 'Руководитель' },
      { key: 'membersCount', header: 'Участники' },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text', required: true },
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
  chat: {
    slug: 'chat',
    title: 'Чат',
    apiEndpoint: '/chat/rooms',
    searchField: 'названию',
    canCreate: false,
    canDelete: false,
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'name', header: 'Название', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'membersCount', header: 'Участники' },
    ],
    formFields: [
      { key: 'name', label: 'Название', type: 'text' },
    ],
  },
  notifications: {
    slug: 'notifications',
    title: 'Уведомления',
    apiEndpoint: '/notifications',
    searchField: 'тексту',
    canEdit: false,
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'title', header: 'Заголовок', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'createdAt', header: 'Создано', sortable: true },
      { key: 'read', header: 'Прочитано', render: (v) => (v ? 'Да' : 'Нет') },
    ],
    formFields: [
      { key: 'title', label: 'Заголовок', type: 'text', required: true },
      { key: 'message', label: 'Сообщение', type: 'textarea', required: true },
      { key: 'type', label: 'Тип', type: 'select', options: [
        { value: 'info', label: 'Информация' },
        { value: 'warning', label: 'Предупреждение' },
        { value: 'urgent', label: 'Срочное' },
      ]},
    ],
  },
  calendar: {
    slug: 'calendar',
    title: 'Календарь',
    apiEndpoint: '/calendar/events',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'title', header: 'Название', sortable: true },
      { key: 'startDate', header: 'Начало', sortable: true },
      { key: 'endDate', header: 'Окончание' },
      { key: 'type', header: 'Тип' },
    ],
    formFields: [
      { key: 'title', label: 'Название', type: 'text', required: true },
      { key: 'startDate', label: 'Начало', type: 'date', required: true },
      { key: 'endDate', label: 'Окончание', type: 'date' },
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
  inspections: {
    slug: 'inspections',
    title: 'Инспекции',
    apiEndpoint: '/inspections',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'title', header: 'Название', sortable: true },
      { key: 'status', header: 'Статус', sortable: true },
      { key: 'date', header: 'Дата', sortable: true },
      { key: 'inspector', header: 'Инспектор' },
    ],
    formFields: [
      { key: 'title', label: 'Название', type: 'text', required: true },
      { key: 'status', label: 'Статус', type: 'select', options: [
        { value: 'planned', label: 'Запланирована' },
        { value: 'in_progress', label: 'В процессе' },
        { value: 'completed', label: 'Завершена' },
      ]},
      { key: 'date', label: 'Дата', type: 'date', required: true },
      { key: 'notes', label: 'Примечания', type: 'textarea' },
    ],
  },
  audit: {
    slug: 'audit',
    title: 'Аудит',
    apiEndpoint: '/audit',
    searchField: 'действию',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'action', header: 'Действие', sortable: true },
      { key: 'user', header: 'Пользователь' },
      { key: 'entity', header: 'Объект' },
      { key: 'createdAt', header: 'Дата', sortable: true },
    ],
    formFields: [],
  },
  reports: {
    slug: 'reports',
    title: 'Отчёты',
    apiEndpoint: '/reports',
    searchField: 'названию',
    columns: [
      { key: 'id', header: 'ID', sortable: true, width: '80px' },
      { key: 'title', header: 'Название', sortable: true },
      { key: 'type', header: 'Тип' },
      { key: 'createdAt', header: 'Создан', sortable: true },
    ],
    formFields: [
      { key: 'title', label: 'Название', type: 'text', required: true },
      { key: 'type', label: 'Тип', type: 'select', options: [
        { value: 'financial', label: 'Финансовый' },
        { value: 'progress', label: 'Прогресс' },
        { value: 'inspection', label: 'Инспекция' },
        { value: 'other', label: 'Прочее' },
      ]},
      { key: 'description', label: 'Описание', type: 'textarea' },
    ],
  },
};

export const MODULE_CATEGORIES: ModuleCategory[] = [
  {
    name: 'Основные',
    modules: [ADMIN_MODULES.users, ADMIN_MODULES.projects, ADMIN_MODULES.tasks, ADMIN_MODULES.clients],
  },
  {
    name: 'Ресурсы',
    modules: [ADMIN_MODULES.materials, ADMIN_MODULES.equipment, ADMIN_MODULES.suppliers, ADMIN_MODULES.documents],
  },
  {
    name: 'Финансы',
    modules: [ADMIN_MODULES.payments, ADMIN_MODULES.budgets, ADMIN_MODULES.acts, ADMIN_MODULES.salaries, ADMIN_MODULES.bonuses],
  },
  {
    name: 'HR',
    modules: [ADMIN_MODULES['employee-documents'], ADMIN_MODULES.leaves, ADMIN_MODULES.attendance, ADMIN_MODULES.teams],
  },
  {
    name: 'Коммуникации',
    modules: [ADMIN_MODULES.chat, ADMIN_MODULES.notifications, ADMIN_MODULES.calendar],
  },
  {
    name: 'Контроль',
    modules: [ADMIN_MODULES.inspections, ADMIN_MODULES.audit, ADMIN_MODULES.reports],
  },
];
